#Custom Seed plugin by Mentagess | Plugin de Custom Seed créé par Mentagess
#  __  __            _                              ____             
# |  \/  | ___ _ __ | |_ __ _  __ _  ___  ___ ___  |  _ \  _____   __
# | |\/| |/ _ \ '_ \| __/ _` |/ _` |/ _ \/ __/ __| | | | |/ _ \ \ / /
# | |  | |  __/ | | | || (_| | (_| |  __/\__ \__ \ | |_| |  __/\ V / 
# |_|  |_|\___|_| |_|\__\__,_|\__, |\___||___/___/ |____/ \___| \_/  
#                             |___/  
#description:
#ENG: This plugin aims to transform a type of block into a so-called mod seed!
#FRA: Ce plugin a pour but de transformer un type de block en graine dit modé!

#id du block | block id
id: 1
#meta du block | block meta
meta: 1

#premier item (id) | first item (id)
item-drop-1: 369
#meta
meta-drop-1: 0
#nombre d'item drop | number of drop items
#64 max
nb-drop-1: 2
#message qui s'affiche quand vous gagnez le premier item | message that appears when you win the first item
tip-drop-1: "Gg tu à gagné une blaze rod"
#chance de drop du premier item | chance to drop the first item
chance-1: 3

item-drop-2: 369
meta-drop-2: 2
nb-drop-2: 1
tip-drop-2: "Gg tu à gagné une blaze rod avec un meta de 1"
#Ceci est la chance au totale c'est à dire si vous mettez à chance-1: 3 et que à chance-max: 100 vous aurrez 97 chances de drop l'item 2 | This is the total chance, i.e. if you put at chance-1: 3 and at chance-max: 100 you will have 97 chances of dropping item 2
chance-max: 100
